#数据微服务
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: data-service
  datasource:
    url: jdbc:mysql://121.42.231.1:3306/heypdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: heypdb
    password: heypdb_0123

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
